// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "d0bc596b-dd8e-4c3c-88f0-3b1ec4dbd7c1");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1613570549);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1613570522);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1613570521);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1613570579);
user_pref("app.update.lastUpdateTime.telemetry_untrustedmodules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir2.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1613570518);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 104);
user_pref("browser.newtabpage.activity-stream.impressionId", "{176ec408-1123-4084-8282-4d64019a23bb}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "yandex");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://yandex.com\",\"label\":\"@яндекс\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"shareURL\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.region.update.updated", 1613570521);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1613570555903");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1613572367903");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1613570527359");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1613592127359");
user_pref("browser.search.region", "TR");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1613570520");
user_pref("browser.slowStartup.averageTime", 1551);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20210208133944");
user_pref("browser.startup.homepage_override.mstone", "85.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1613570520);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Yandex");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1613570521449");
user_pref("distribution.iniFile.exists.appversion", "85.0.2");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "7eafe3142b434a7c88d872cb22ef5823");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210208133944");
user_pref("extensions.lastAppVersion", "85.0.2");
user_pref("extensions.lastPlatformVersion", "85.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_picture_in_picture_overrides", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"54f596e8-6a9d-46f8-ac73-5cbe5eba9080\",\"formautofill@mozilla.org\":\"757310ed-c5a0-4ed8-9b3a-e113aad972c3\",\"screenshots@mozilla.org\":\"b01b0a7f-d6d6-4d42-8f96-9ebf5b31f824\",\"webcompat-reporter@mozilla.org\":\"ce2c41b4-df39-40f3-8d96-b188a70bca95\",\"webcompat@mozilla.org\":\"6b485f1d-f147-4996-a6aa-902ca5f736f7\",\"default-theme@mozilla.org\":\"189639bb-17ef-4494-bb14-d4709f21906e\",\"google@search.mozilla.org\":\"03ad760f-4b56-4eb7-a280-81bd25b94fba\",\"wikipedia@search.mozilla.org\":\"fe1015ff-ef96-4377-8b8a-f5938f5db487\",\"yandex@search.mozilla.org\":\"5b7aa35a-0f29-4145-8638-d891c41487c8\",\"ddg@search.mozilla.org\":\"19ded88a-8577-48ef-b404-309c4aab669f\"}");
user_pref("gfx-shader-check.build-version", "20210208133944");
user_pref("gfx-shader-check.device-id", "0x1c82");
user_pref("gfx-shader-check.driver-version", "27.21.14.6140");
user_pref("gfx.crash-guard.status.wmfvpxvideo", 2);
user_pref("gfx.crash-guard.wmfvpxvideo.appVersion", "85.0.2");
user_pref("gfx.crash-guard.wmfvpxvideo.deviceID", "0x1c82");
user_pref("gfx.crash-guard.wmfvpxvideo.driverVersion", "27.21.14.6140");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.advanced-layers", false);
user_pref("sanity-test.device-id", "0x1c82");
user_pref("sanity-test.driver-version", "27.21.14.6140");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20210208133944");
user_pref("sanity-test.webrender.force-disabled", false);
user_pref("security.sandbox.content.tempDirSuffix", "{f7e888d1-19b5-4ca4-a679-c359fb018aab}");
user_pref("security.sandbox.plugin.tempDirSuffix", "{d53ab618-9690-4965-bd13-f5a43026e485}");
user_pref("toolkit.startup.last_success", 1613570518);
user_pref("toolkit.telemetry.cachedClientID", "fff611f1-4f6e-4614-a94e-f991d5ec84fb");
user_pref("toolkit.telemetry.previousBuildID", "20210208133944");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
